# inheritance concept
- name: variables to print 
  hosts: web
  vars:
    COURSE: "Devops with aws"
    DURATION: "120 Hrs"
    TRAINER: "Siva Kumar"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi,I am learning: {{COURSE}},Duration is: {{DURATION}},Trainer is: {{TRAINER}}"   

  - name: print the information again
    vars: 
      COURSE: "Ansible"
      DURATION: "120 Hrs"
      TRAINER: "Siva Kumar"
    ansible.builtin.debug:
      msg: "Hi,I am learning: {{COURSE}},Duration is: {{DURATION}},Trainer is: {{TRAINER}}"      

  - name: print the information again
    ansible.builtin.debug:
      msg: "Hi,I am learning: {{COURSE}},Duration is: {{DURATION}},Trainer is: {{TRAINER}}"      