- name : chcek the number is less than 10 or not
  hosts: localhost
  # connection: local
  vars_prompt:
  - name: number
    prompt: Please enter the number
    private: false #not confidential
  
  tasks:
  - name: print the number if its less than 10
    debug:
      msg: "Entered number {{ number }} is less than 10"
    when: number | int < 10 #conditional expression

  - name: print the number is greater than or equal to 10
    debug:
      msg: "Entered number {{ number }} is greater than or equal to 10"
    when: number | int >= 10

  - name: print the number is greated than 10
    debug:
      msg: "Entered number {{ number }} is greated than 10"
    when: number | int > 10    


   
# - name: Check if a number is less than or greater than a specified value
#   hosts: localhost
#   vars:
#     number_to_check: 10
#     comparison_value: 20

#   tasks:
#     - name: Check if number is less than comparison value
#       debug:
#         msg: "The number {{ number_to_check }} is less than {{ comparison_value }}."
#       when: number_to_check < comparison_value

#     - name: Check if number is greater than comparison value
#       debug:
#         msg: "The number {{ number_to_check }} is greater than or equal to {{ comparison_value }}."
#       when: number_to_check >= comparison_value


- name: check a number is less than 10 or not
  hosts: local
  connection: local
  vars_prompt:
  - name: my_number
    prompt: Please enter the number
    private: false # not confidential
  # vars:
  #   my_number: 139 # number
  tasks:
  - name: print this if less than 10
    ansible.builtin.debug:
      msg: "Given number {{ my_number }} is less than 10"
    when: my_number | int < 10 # conditional expression

  - name: print this if greater than or equal to 10
    ansible.builtin.debug:
      msg: "Given number {{ my_number }} greater than or equal to 10"
    when: my_number | int >= 10