# install nginx based on facts
- name: Install nginx
  hosts: localhost
  become: yes
  tasks:
  - name: print the stat
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"
  
  - name: Install nginx if RedHat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"

  - name: Install nginx if Debian
    ansible.builtin.apt:         
      name: nginx
      state: present
    when: ansible_os_family == "Debian"  