- name: command vs shell
  hosts: localhost
  tasks:
  # - name: execute the command
  #   ansible.builtin.command: ls -ltr > /tmp/output.txt # login to the server and execute command inside
  #   ignore_error: true # command module, just issues the command

  - name: execute the command
    ansible.builtin.shell: ls -ltr > /tmp/output.txt  

  - name: execute the command
    ansible.builtin.shell: ps -ef | grep ssh
    register: output

  - name: execute the command
    ansible.builtin.command: ps -ef | grep ssh  
    register: output

 